version: 2
updates:

  # Python packages
  - package-ecosystem: "pip"
    directory: "/using-huey"
    schedule:
      interval: "daily"
    target-branch: "compatible-libraries"

  - package-ecosystem: "pip"
    directory: "/using-apscheduler"
    schedule:
      interval: "daily"
    target-branch: "compatible-libraries"
    
  - package-ecosystem: "pip"
    directory: "/using-celery"
    schedule:
      interval: "daily"
    target-branch: "compatible-libraries"
    

  # Ruby packages
  - package-ecosystem: "bundler"
    directory: "/using-sidekiq"
    schedule:
      interval: "daily"
    target-branch: "compatible-libraries"

  - package-ecosystem: "bundler"
    directory: "/using-resque"
    schedule:
      interval: "daily"
    target-branch: "compatible-libraries"
      

  # Rust packages
  - package-ecosystem: "cargo"
    directory: "/using_redis-rs"
    schedule:
      interval: "daily"
    target-branch: "compatible-libraries"